package:
    name: dis
    version: "0.0+00000000"
    # version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    path: ../

requirements:
    host:
        - numpy
        - python
        - numba
        - scipy
    run:
        - numpy
        - python
        - numba
        - sphinx
        - recommonmark
        - sphinx_rtd_theme
        - scipy
        - pyyaml
        - lhapdf
        - apfel

test:
    requires:
        - pytest
        - conda-build
    commands:
        - pytest --pyargs yadism

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"

about:
    home: https://github.com/N3PDF/dis
    license: GPLv3
    summary: "Yet Another Deep Inelastic Scattering Module"
