name: docs

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "*"

jobs:
  deploy-ghpages:
    runs-on: ubuntu-latest
    strategy:
      #      max-parallel: 2
      matrix:
        python-version: [3.7]
      fail-fast: false

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.ALE_DIS_PAT }}
          submodules: "true"
      - name: Set up Node 🧶
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Set up Python ${{ matrix.python-version }} 🐍
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package 📦
        run: |
          # install pip
          python -m pip install --upgrade pip
          # install yadism
          pip install .
      - name: Build 🔨
        run: |
          pip install -r doc_requirements.txt
          sudo apt-get install graphviz
          cd docs/home-page
          yarn
          make
          cd ../sphinx/
          make html
      - name: Save files 💾
        run: |
          ls
          ls build
          mv build/html ~
          mv ../home-page ~
          mv ../_assets ~
      - name: Prepare deployment ⌛
        run: |
          # fetch all branches
          git fetch --depth=1
          git checkout gh-pages
          github_ref="${{ github.ref }}"
          dest_dir=$(echo $github_ref | rev | cut -d "/" -f 1 | rev)
          if [ "$dest_dir" = "master" ]; then
            dest_dir="stable"
          fi
          mv ~/home-page/* .
          mv ~/_assets .
          mv ~/html $dest_dir
      - name: Deploy 🚀
        #uses: JamesIves/github-pages-deploy-action@releases/v3
        #with:
        #ACCESS_TOKEN: ${{ secrets.ALE_DIS_PAT }}
        #BRANCH: gh-pages # The branch the action should deploy to.
        #FOLDER: "docs/sphinx/build/html" # The folder the action should deploy.
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: "Currently deploying: ${{ github.ref }}"
          ref: "gh-pages"
        env:
          GITHUB_TOKEN: ${{ secrets.ALE_DIS_PAT }}
