name: yadism-regression

on:
  push:
    branches-ignore:
      - "*docs*"

jobs:
  # build is the <job_id>
  build:
    runs-on: ubuntu-latest
    strategy:
#      max-parallel: 2
      matrix:
        python-version: [3.7, 3.8]
      fail-fast: false

    steps:
      # checkout the repo on the github runner
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} 🐍
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # install the actual python package 'yadism'
      - name: Install yadism
        run: |
          pip install .
      - name: Prepare Test environment
        run: |
          # install packages needed for testing
          pip install -r test_requirements.txt
          # download regression db
          wget https://gist.githubusercontent.com/felixhekhorn/f89d04db0565e8f880f2547be281fbdf/raw/73c56ff8e038887d8487183d886009d44ffd208b/regression.json
          mv regression.json benchmarks/data/
      #  run the test with 'pytest'
      - name: Test yadism
        run: |
          # run tests
          pytest -m regression
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: regression
          name: codecov-umbrella
          fail_ci_if_error: true
